# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Coin Flip Games - Legal
email: hi@coinflipgames.co
description: Coin Flip Games - Legalese and Compliance
baseurl: "http://coinflipgamesllc.github.io/legal"
url: "http://coinflipgamesllc.github.io/legal"
twitter_username: coinflipgames
github_username:  coinflipgamesllc

# Build settings
markdown: kramdown
